// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: chat_demo.proto
#ifndef GRPC_chat_5fdemo_2eproto__INCLUDED
#define GRPC_chat_5fdemo_2eproto__INCLUDED

#include "chat_demo.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc_impl {
class CompletionQueue;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc_impl

namespace grpc {
namespace experimental {
template <typename RequestT, typename ResponseT>
class MessageAllocator;
}  // namespace experimental
}  // namespace grpc

namespace chatDemo {

class ChatService final {
 public:
  static constexpr char const* service_full_name() {
    return "chatDemo.ChatService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::chatDemo::Connect, ::chatDemo::Connect>> ClientSide(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::chatDemo::Connect, ::chatDemo::Connect>>(ClientSideRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::chatDemo::Connect, ::chatDemo::Connect>> AsyncClientSide(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::chatDemo::Connect, ::chatDemo::Connect>>(AsyncClientSideRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::chatDemo::Connect, ::chatDemo::Connect>> PrepareAsyncClientSide(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::chatDemo::Connect, ::chatDemo::Connect>>(PrepareAsyncClientSideRaw(context, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void ClientSide(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::chatDemo::Connect,::chatDemo::Connect>* reactor) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientReaderWriterInterface< ::chatDemo::Connect, ::chatDemo::Connect>* ClientSideRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::chatDemo::Connect, ::chatDemo::Connect>* AsyncClientSideRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::chatDemo::Connect, ::chatDemo::Connect>* PrepareAsyncClientSideRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReaderWriter< ::chatDemo::Connect, ::chatDemo::Connect>> ClientSide(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::chatDemo::Connect, ::chatDemo::Connect>>(ClientSideRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::chatDemo::Connect, ::chatDemo::Connect>> AsyncClientSide(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::chatDemo::Connect, ::chatDemo::Connect>>(AsyncClientSideRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::chatDemo::Connect, ::chatDemo::Connect>> PrepareAsyncClientSide(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::chatDemo::Connect, ::chatDemo::Connect>>(PrepareAsyncClientSideRaw(context, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void ClientSide(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::chatDemo::Connect,::chatDemo::Connect>* reactor) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientReaderWriter< ::chatDemo::Connect, ::chatDemo::Connect>* ClientSideRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::chatDemo::Connect, ::chatDemo::Connect>* AsyncClientSideRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::chatDemo::Connect, ::chatDemo::Connect>* PrepareAsyncClientSideRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ClientSide_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ClientSide(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::chatDemo::Connect, ::chatDemo::Connect>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_ClientSide : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ClientSide() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ClientSide() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ClientSide(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::chatDemo::Connect, ::chatDemo::Connect>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestClientSide(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::chatDemo::Connect, ::chatDemo::Connect>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ClientSide<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_ClientSide : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_ClientSide() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc_impl::internal::CallbackBidiHandler< ::chatDemo::Connect, ::chatDemo::Connect>(
          [this] { return this->ClientSide(); }));
    }
    ~ExperimentalWithCallbackMethod_ClientSide() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ClientSide(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::chatDemo::Connect, ::chatDemo::Connect>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::experimental::ServerBidiReactor< ::chatDemo::Connect, ::chatDemo::Connect>* ClientSide() {
      return new ::grpc_impl::internal::UnimplementedBidiReactor<
        ::chatDemo::Connect, ::chatDemo::Connect>;}
  };
  typedef ExperimentalWithCallbackMethod_ClientSide<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ClientSide : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ClientSide() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ClientSide() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ClientSide(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::chatDemo::Connect, ::chatDemo::Connect>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ClientSide : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ClientSide() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ClientSide() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ClientSide(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::chatDemo::Connect, ::chatDemo::Connect>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestClientSide(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_ClientSide : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_ClientSide() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc_impl::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this] { return this->ClientSide(); }));
    }
    ~ExperimentalWithRawCallbackMethod_ClientSide() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ClientSide(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::chatDemo::Connect, ::chatDemo::Connect>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::experimental::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* ClientSide() {
      return new ::grpc_impl::internal::UnimplementedBidiReactor<
        ::grpc::ByteBuffer, ::grpc::ByteBuffer>;}
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace chatDemo


#endif  // GRPC_chat_5fdemo_2eproto__INCLUDED
